// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibtqysxchuqcqcafbyzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlidHF5c3hjaHVxY3FjYWZieXpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTI2ODksImV4cCI6MjA2OTI4ODY4OX0.51ABZfrIUef9YD2NM6HdMIW4SLoHnifdyUsk2TG7xXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});